FROM ubuntu:24.04@sha256:66460d557b25769b102175144d538d88219c077c678a49af4afca6fbfc1b5252
# vi: tw=0

# The standard Ubuntu 24.04 Github runner comes with lcov 2.0, which
# behaves differently to lcov 2.3 on MacOS. Installing lcov takes several
# minutes, so this Docker image is used to build it once and reuse it
# in the Github workflow.

# The larger Dockerfile (also including vim and man pages) is for local
# development on Macos.

# From
# https://github.com/banach-space/llvm-tutor/blob/main/Dockerfile_ubuntu_apt:
# As `tzdata` gets installed automatically (AFAIK, Python depends on it), it
# will interrupt the set-up with a question about the time-zone to use. However,
# this is a non-interactive sessions and that won't work. Work around it by
# setting the time-zone here.
ENV TZ=Europe/Berlin
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

ARG LLVM_VERSION=19

RUN apt-get update && apt-get install -y --no-install-recommends \
    # software-properties-common for apt-add-repository
    software-properties-common \
    sudo \
    # git for git-based cmake dependencies (e.g. spdlog, cli11)
    git \
    wget \
    cmake \
    build-essential \
    libspdlog-dev libgtest-dev libgmock-dev libcli11-dev \
    cpanminus && \
    wget -qO - https://apt.llvm.org/llvm-snapshot.gpg.key | gpg --dearmor > /etc/apt/trusted.gpg.d/llvm-snapshot.gpg && \
    apt-add-repository "deb http://apt.llvm.org/noble/ llvm-toolchain-noble-${LLVM_VERSION} main" && \
    apt-get update && apt-get install -y --no-install-recommends \
    llvm-${LLVM_VERSION} llvm-${LLVM_VERSION}-tools clang-${LLVM_VERSION} \
    libncurses-dev libncurses6 \
    libclang-rt-${LLVM_VERSION}-dev && \
    apt-get purge -y --auto-remove software-properties-common && \
    rm -rf /var/lib/apt/lists/* && \
    cpanm --notest Capture::Tiny DateTime Devel::Cover Digest::MD5 File::Spec JSON::XS Memory::Process Module::Load::Conditional Scalar::Util Time::HiRes TimeDate && \
    rm -rf ~/.cpanm && \
    cd /tmp && \
    wget -qO lcov.tar.gz https://github.com/linux-test-project/lcov/releases/download/v2.3/lcov-2.3.tar.gz && \
    tar -xzf lcov.tar.gz && \
    cd /tmp/lcov-2.3 && \
    make install && \
    rm -rf /tmp/lcov-2.3 lcov.tar.gz

RUN echo "export PATH=$PATH:/usr/lib/llvm-${LLVM_VERSION}/bin" >> /root/.bashrc && \
    echo "set -o vi" >> /root/.bashrc
ENV PATH="${PATH}:/usr/lib/llvm-${LLVM_VERSION}/bin"
