# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: CMake on multiple platforms

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    # container: ghcr.io/andreaswachowski/ubuntu-cpp:latest

    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]
        c_compiler: [gcc, clang]
        include:
          - c_compiler: gcc
            cpp_compiler: g++
          - c_compiler: clang
            cpp_compiler: clang++
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libspdlog-dev libgtest-dev libcli11-dev cpanminus
          sudo cpanm Capture::Tiny DateTime Devel::Cover Digest::MD5 File::Spec JSON::XS Memory::Process Module::Load::Conditional Scalar::Util Time::HiRes TimeDate
          cd /tmp
          wget https://github.com/linux-test-project/lcov/releases/download/v2.3/lcov-2.3.tar.gz
          tar -xzf lcov-2.3.tar.gz
          cd /tmp/lcov-2.3
          sudo make install
          lcov --version

      - name: Add LLVM to PATH
        run: |
          echo "/usr/lib/llvm-18/bin" >> $GITHUB_PATH

      - name: Build project
        uses: ./.github/actions/build
        with:
          os: ubuntu
          build_output_dir: ${{ github.workspace }}/build
          c_compiler: ${{ matrix.c_compiler }}
          cpp_compiler: ${{ matrix.cpp_compiler }}
          build_type: ${{ matrix.build_type }}

  build-macos:
    runs-on: macos-15
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]
        c_compiler: [clang]
        include:
          - c_compiler: clang
            cpp_compiler: clang++

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew update
          brew install spdlog googletest cli11 lcov

      - name: Add LLVM to PATH
        run: |
          echo "$(brew --prefix llvm@18)/bin" >> $GITHUB_PATH

      - name: Build and test project, measure test coverage
        uses: ./.github/actions/build
        with:
          os: macos
          build_output_dir: ${{ github.workspace }}/build
          c_compiler: ${{ matrix.c_compiler }}
          cpp_compiler: ${{ matrix.cpp_compiler }}
          build_type: ${{ matrix.build_type }}
